export const JOIN_WITH_FACEBOOK_SUCCESS = 'JOIN_WITH_FACEBOOK_SUCCESS';
export const JOIN_WITH_FACEBOOK_FAILURE = 'JOIN_WITH_FACEBOOK_FAILURE';

export const JOIN_WITH_INSTAGRAM_SUCCESS = 'JOIN_WITH_INSTAGRAM_SUCCESS';
export const JOIN_WITH_INSTAGRAM_FAILURE = 'JOIN_WITH_INSTAGRAM_FAILURE';

export const SIGN_IN_WITH_FACEBOOK_SUCCESS = 'SIGN_IN_WITH_FACEBOOK_SUCCESS';
export const SIGN_IN_WITH_FACEBOOK_FAILURE = 'SIGN_IN_WITH_FACEBOOK_FAILURE';

export const SIGN_IN_WITH_INSTAGRAM_SUCCESS = 'SIGN_IN_WITH_INSTAGRAM_SUCCESS';
export const SIGN_IN_WITH_INSTAGRAM_FAILURE = 'SIGN_IN_WITH_INSTAGRAM_FAILURE';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
